name: Update README with .md file list

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Give write permissions to the contents of the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of markdown files
      id: get_files
      run: |
        files=$(find . -name "*.md" -not -path "./.git/*" -not -name "README.md")
        echo "$files" > files.txt

    - name: Update README.md
      run: |
        # Read the current README.md content
        readme_content=$(cat README.md)
        
        # Create a markdown list of links
        markdown_list=""
        while IFS= read -r file; do
          file_name=$(basename "$file")
          markdown_list+="- [${file_name}](${file})\n"
        done < files.txt

        # Add the new list to the README.md file
        updated_content="${readme_content}\n\n## List of Markdown Files\n${markdown_list}"

        # Write the updated content back to README.md
        echo -e "$updated_content" > README.md

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with .md file list"
        git push
