name: Update README with .md file tree

on:
  push:
    branches:
      - nodejs
  pull_request:
    branches:
      - nodejs

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update_readme.py
        run: |
          python3 update_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with Markdown file tree"
          git push
