name: Update README.md with .md files

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get list of .md files
      run: |
        # Find all .md files and save them to a variable
        md_files=$(find . -name "*.md" -not -path "./README.md" -not -path "*/node_modules/*" -not -path "*/.git/*" -print)
        
        # Format the list with markdown hyperlinks
        md_links=""
        for file in $md_files; do
          file_name=$(basename "$file")
          md_links="$md_links\n- [$file_name]($file)"
        done
        
        # Create a markdown list in a file to be inserted into README
        echo -e "$md_links" > md_files_list.md

    - name: Update README.md
      run: |
        # Add the list of .md files to the README.md
        list_of_files=$(cat md_files_list.md)

        # Add or update the section in the README.md file
        sed -i "/## Markdown Files List/i ## Markdown Files List\n$list_of_files\n" README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md with .md files list"
        git push
