name: Update README with .md file list

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Trigger on PRs as well if necessary

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Give write permissions to the contents of the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get list of markdown files
      id: get_files
      run: |
        files=$(find . -name "*.md" -not -path "./.git/*" -not -name "README.md")
        echo "$files" > files.txt

    - name: Read current README.md and remove old markdown file list
      id: update_readme
      run: |
        # Read the current README.md content
        readme_content=$(cat README.md)
        
        # Remove any existing markdown list of files section (if present)
        updated_content=$(echo "$readme_content" | sed '/## List of Markdown Files/,$d')

        # Create a new markdown list of links
        markdown_list=""
        while IFS= read -r file; do
          file_name=$(basename "$file")
          markdown_list+="- [${file_name}](${file})\n"
        done < files.txt

        # Add the new list to the updated content
        updated_content="${updated_content}\n\n## List of Markdown Files\n${markdown_list}"

        # Write the updated content back to README.md
        echo -e "$updated_content" > README.md

    - name: Commit and push changes
      run: |
        git config user.name "maheshndev"
        git config user.email "maheshnarsale@outlook.com"
        git add README.md
        git commit -m "Update README with new .md file list"
        git push
