name: Update README with .md files

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "maheshndev"
        git config --global user.email "maheshnarsale@outlook.com"

    - name: Find all .md files and update README
      run: |
        # Get a list of all .md files in the current branch
        md_files=$(find . -type f -name "*.md" | tr '\n' ' ')
        echo "Found .md files: $md_files"
        # Update the README file (example: append the list)
        echo "### Latest .md Files" >> README.md
        echo "$md_files" >> README.md
        
    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Update README with latest .md files"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Push changes
      run: |
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
