name: Update README with .md file list

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows modification of the repository contents
      admin: write     # Admin permissions for repository operations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of markdown files
        id: get_files
        run: |
          files=$(find . -name "*.md" -not -path "./.git/*" -not -name "README.md")
          echo "$files" > files.txt

      - name: Update README with file list
        run: |
          # Process and update README.md as described earlier
          ...
          git add README.md
          git commit -m "Update README with new .md file list"
          git push
