name: Update README with Markdown Files

on:
  push:
    branches:
      - main  # Trigger this on push to main (or your default branch)

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get list of .md files in the current branch
        run: |
          # Find all .md files in the repository, excluding README.md itself
          md_files=$(find . -name "*.md" -not -path "./README.md")
          echo "$md_files" > markdown_files.txt
        
      - name: Generate the list of .md files as markdown links
        run: |
          # Generate markdown-formatted links for each .md file
          links=""
          while IFS= read -r file; do
            filename=$(basename "$file")
            links+="* [$filename]($file)\n"
          done < markdown_files.txt
          echo -e "$links" > links.md

      - name: Update README.md with the list of markdown files
        run: |
          # Read the current README.md and append the list of .md files to it
          echo -e "\n## List of Markdown Files\n$(cat links.md)" >> README.md

      - name: Commit changes to README.md
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with list of markdown files"
          git push
